---
- name: update apt cache
  apt:
    update-cache: yes
  when: ansible_os_family == 'Debian'

- name: restart ceph mons
  include: "{{ playbook_dir }}/roles/ceph-common/handlers/restart-mon.yml"

- name: restart ceph osds
  include: "{{ playbook_dir }}/roles/ceph-common/handlers/restart-osd.yml"

- name: restart ceph mdss
  include: "{{ playbook_dir }}/roles/ceph-common/handlers/restart-mds.yml"

- name: restart ceph rgws
  include: "{{ playbook_dir }}/roles/ceph-common/handlers/restart-rgw.yml"

- name: restart apache2
  service:
    name: apache2
    state: restarted
    enabled: yes
  when:
    - ansible_os_family == 'Debian'
    - rgw_group_name in group_names

- name: restart apache2
  service:
    name: httpd
    state: restarted
    enabled: yes
  when:
    - ansible_os_family == 'RedHat'
    - rgw_group_name in group_names

- name: restart ceph nfss
  service:
    name: nfs-ganesha
    state: restarted
  when:
    - nfs_group_name in group_names
