---
- name: restart ceph mdss on ubuntu
  command: initctl restart ceph-mds cluster={{ cluster }} id={{ ansible_hostname }}
  # serial: 1 would be the proper solution here, but that can only be set on play level
  # upstream issue: https://github.com/ansible/ansible/issues/12170
  run_once: true
  with_items: "{{ groups[mds_group_name] }}"
  delegate_to: "{{ item }}"
  when:
    - socket.rc == 0
    - ansible_distribution == 'Ubuntu'
    - not use_systemd
    - mds_group_name in group_names

- name: restart ceph mdss
  command: service ceph restart mds
  # serial: 1 would be the proper solution here, but that can only be set on play level
  # upstream issue: https://github.com/ansible/ansible/issues/12170
  run_once: true
  with_items: "{{ groups[mds_group_name] }}"
  delegate_to: "{{ item }}"
  when:
    - socket.rc == 0
    - ansible_distribution != 'Ubuntu'
    - use_systemd
    - mds_group_name in group_names
    - ceph_release_num.{{ ceph_release }} < ceph_release_num.infernalis

- name: restart ceph mdss with systemd
  service:
    name: ceph-mds@{{ mds_name }}
    state: restarted
  # serial: 1 would be the proper solution here, but that can only be set on play level
  # upstream issue: https://github.com/ansible/ansible/issues/12170
  run_once: true
  with_items: "{{ groups[mds_group_name] }}"
  delegate_to: "{{ item }}"
  when:
    - socket.rc == 0
    - use_systemd
    - mds_group_name in group_names
    - ceph_release_num.{{ ceph_release }} > ceph_release_num.hammer
