---
- name: restart ceph mons
  command: service ceph restart mon
  # serial: 1 would be the proper solution here, but that can only be set on play level
  # upstream issue: https://github.com/ansible/ansible/issues/12170
  run_once: true
  with_items: "{{ groups[mon_group_name] }}"
  delegate_to: "{{ item }}"
  when:
    - socket.rc == 0
    - ansible_distribution != 'Ubuntu'
    - mon_group_name in group_names
    - ceph_release_num.{{ ceph_release }} < ceph_release_num.infernalis

- name: restart ceph mons with systemd
  service:
    name: ceph-mon@{{ monitor_name }}
    state: restarted
  # serial: 1 would be the proper solution here, but that can only be set on play level
  # upstream issue: https://github.com/ansible/ansible/issues/12170
  run_once: true
  with_items: "{{ groups[mon_group_name] }}"
  delegate_to: "{{ item }}"
  when:
    - socket.rc == 0
    - use_systemd
    - mon_group_name in group_names
    - ceph_release_num.{{ ceph_release }} > ceph_release_num.hammer

- name: restart ceph mons on ubuntu
  command: initctl restart ceph-mon cluster={{ cluster }} id={{ monitor_name }}
  # serial: 1 would be the proper solution here, but that can only be set on play level
  # upstream issue: https://github.com/ansible/ansible/issues/12170
  run_once: true
  with_items: "{{ groups[mon_group_name] }}"
  delegate_to: "{{ item }}"
  when:
    - socket.rc == 0
    - ansible_distribution == 'Ubuntu'
    - not use_systemd
    - mon_group_name in group_names

- name: validate monitors
  include: validate-mon.yml
  when: mon_group_name in group_names
