---
- name: restart ceph rgws on ubuntu
  command: initctl restart radosgw cluster={{ cluster }} id=rgw.{{ ansible_hostname }}
  # serial: 1 would be the proper solution here, but that can only be set on play level
  # upstream issue: https://github.com/ansible/ansible/issues/12170
  run_once: true
  with_items: "{{ groups[rgw_group_name] }}"
  delegate_to: "{{ item }}"
  when:
    - socketrgw.rc == 0
    - ansible_distribution == 'Ubuntu'
    - not use_systemd
    - rgw_group_name in group_names

- name: restart ceph rgws
  command: /etc/init.d/radosgw restart
  # serial: 1 would be the proper solution here, but that can only be set on play level
  # upstream issue: https://github.com/ansible/ansible/issues/12170
  run_once: true
  with_items: "{{ groups[rgw_group_name] }}"
  delegate_to: "{{ item }}"
  when:
    - socketrgw.rc == 0
    - ansible_distribution != 'Ubuntu'
    - rgw_group_name in group_names
    - ceph_release_num.{{ ceph_release }} < ceph_release_num.infernalis

- name: restart ceph rgws on red hat
  command: /etc/init.d/ceph-radosgw restart
  # serial: 1 would be the proper solution here, but that can only be set on play level
  # upstream issue: https://github.com/ansible/ansible/issues/12170
  run_once: true
  with_items: "{{ groups[rgw_group_name] }}"
  delegate_to: "{{ item }}"
  when:
    - socketrgw.rc == 0
    - ansible_os_family == 'RedHat'
    - rgw_group_name in group_names
    - ceph_release_num.{{ ceph_release }} < ceph_release_num.infernalis

- name: restart ceph rgws with systemd
  service:
    name: ceph-rgw@{{ ansible_hostname }}
    state: restarted
  # serial: 1 would be the proper solution here, but that can only be set on play level
  # upstream issue: https://github.com/ansible/ansible/issues/12170
  run_once: true
  with_items: "{{ groups[rgw_group_name] }}"
  delegate_to: "{{ item }}"
  when:
    - socketrgw.rc == 0
    - use_systemd
    - rgw_group_name in group_names
    - ceph_release_num.{{ ceph_release }} > ceph_release_num.hammer
